<?php
function guardarProducto(mysqli $conexion, ?int $id = null): array {
    $datos=['nombre_producto'=>trim($_POST['nombre_producto']??''),'descripcion'=>trim($_POST['descripcion']??''),'precio'=>(float)($_POST['precio']??-1),'cantidad'=>(int)($_POST['cantidad']??-1),'id_categoria'=>(int)($_POST['id_categoria']??0)];
    if($datos['nombre_producto']==='' || $datos['precio']<0 || $datos['cantidad']<0 || !$datos['id_categoria']) return [$datos,'Completa todos los campos correctamente.'];
    if($id) { $s=$conexion->prepare('UPDATE productos SET nombre_producto=?,descripcion=?,precio=?,cantidad=?,id_categoria=? WHERE id_producto=?'); $s->bind_param('ssdiii',$datos['nombre_producto'],$datos['descripcion'],$datos['precio'],$datos['cantidad'],$datos['id_categoria'],$id); }
    else { $s=$conexion->prepare('INSERT INTO productos (nombre_producto,descripcion,precio,cantidad,id_categoria) VALUES (?,?,?,?,?)'); $s->bind_param('ssdii',$datos['nombre_producto'],$datos['descripcion'],$datos['precio'],$datos['cantidad'],$datos['id_categoria']); }
    return [$datos,$s->execute() ? null : 'No se pudo guardar el producto.'];
}
function camposProducto(array $p,array $categorias,string $accion): void { ?>
<form method="post" class="formulario-card mx-auto"><label class="form-label">Nombre</label><input class="form-control mb-3" name="nombre_producto" value="<?php echo e($p['nombre_producto']??''); ?>" required><label class="form-label">Descripción</label><textarea class="form-control mb-3" name="descripcion" required><?php echo e($p['descripcion']??''); ?></textarea><div class="row"><div class="col"><label class="form-label">Precio</label><input class="form-control mb-3" name="precio" type="number" step="0.01" min="0" value="<?php echo e((string)($p['precio']??'')); ?>" required></div><div class="col"><label class="form-label">Stock</label><input class="form-control mb-3" name="cantidad" type="number" min="0" value="<?php echo e((string)($p['cantidad']??'')); ?>" required></div></div><label class="form-label">Categoría</label><select class="form-select mb-4" name="id_categoria" required><?php foreach($categorias as $c): ?><option value="<?php echo $c['id_categoria']; ?>" <?php echo (($p['id_categoria']??0)==$c['id_categoria'])?'selected':''; ?>><?php echo e($c['nombre_categoria']); ?></option><?php endforeach; ?></select><button class="btn btn-principal w-100"><?php echo $accion; ?></button></form><?php }
